[server]
headless = true
enableCORS = false

[client]
showErrorDetails = true

[theme]
primaryColor="#F63366"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"

[runner]
fastReruns = true

[general]
streamlitVersion = "1.32.0"
