[gcp_service_account]
type = "service_account"
project_id = "my-project-schedule-458816"
private_key_id = "8f47521a98fe065c57fc86e93d38b28c84a33fce"
private_key = "-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCq07gu8skiLw4c
+bSxf90ACJor/AT8e6PZMvO3qTgmkP+1zJTsu/Q9eXOb19QyXdyesIaNwRxWY7z5
2quX8EMPkDwSV/j/q0nbVa/isJSsKuGe7RFyYUY1NNhbBo7MU17ci6bZnwDlw+7R
RPgcxiaPbr2R9+JCXTIb9UGoqoi3qB7DflQewM/2KmQ8VHvf2IiIs4Rd0Zdx4G11
adz7R5rL+P5mXpvvDv4mTwmnUDERp+7Ut1k1G+myZ9pxo/TDFFpYd4VXeVptfFeg
EsfOOuqd9S2gZVacfYb8ybqUeHGxh0TqJLtk/AtGX1FQA0R4IN+UGC5lTPHlfi/9
ps/6elv9AgMBAAECggEAKN0pLdfnq9z4Qg+svRoyZm/oW3W3xqMX/Jze5rQc6cLd
XKKiDGhgwnTjZigQy3SfEjn1kgLcMcE9o0I/MoMns5kj+ZpgRt61dfmvL6nggrfm
TXN17TfeSNuJlurAbZnS8yyX/u51k0EVx6s5M/7lmgGaaQjUb94l3sDCUmPq/Q2e
pHp2wh0vrMqA6H86GLtO49vEQG5jBVwnebZH2J/nMzXcHP0G3St2LtTWTykp3bX9
YUrD73uAOTaPZjVxkLpDU3cN+xJPC1O7PvjIOpYM2Th16BiYpvJ5GZxyJh3QCcK3
nt+U8hUEQ8pHy16GgWVdfISUyFIVkBCDSE6Uv+TEsQKBgQDoam6n9c41XeC/NNzq
9NMBTOR1R/RvTEZ4NHUXFAUNMG4CU+VPszk89l6ydsGbBPQW2EVlACACJ0P3iwuC
NONaB25KZBCQs8el6qqSXxbyphHk9mup086gxpGNI6Fbb9/EvyEFIAbv44oqrvkZ
dbLLSaNEnORQsa6oU8sulaa+0QKBgQC8KV6WrnMVOp+ZbVgMf+Tnev4r6FsOpxUc
6GO1vi3nRkcq3+t4o2gx6ZZfGe7cFqQslYfkkUl1IuOBf+xEEBcoumMYjQcHudT7
/vIvS+OSFbVa9+H+RmnVVHTm+4Wz6mLGuMZbdHCax2aJzJKfX8EtaVSUh1ejBEAE
eNXSAcKNbQKBgQDJqI+a7IyfgXUgcp28v/DVkAIqQOS2LVh3tAxkmdpIN108Z87v
+HIRkzNXZfNWrlWb/Ms5d4JOXAN9Jgg2Ue1ykEACDBDTfSodrB+UIS2oHLAqGiYQ
lNcUaTahX+kBjXB7JdtgtwlN3ABmSKuai6U2/g3L2tW/rmv9YbdKFE86AQKBgAzo
iaSssxhxvSE5byDsZTe8KFO6zQRkUf55st10/pEvMRKv6eeMzkkeTUKY9NoEc57b
Y0c68F8o1ZK8w+ince9JWiMFCcZt6T6gbtzvx9ztwFNNTiOzkO8hrCNsfe+p1Lzt
UC5V/qOfqlkpv6VPXGFRKIxH/KsiT4H/CCwwErjBAoGAe4CvUFkrOuLKHhQAWqlv
R8fp30X1kSONcTziTPbi/bi8t735BFekoAKDmn1i3TR/Rv/FIQW4qTZ1v/AEg+lO
enJQndlxJryrk7iHEMDYSBpeGQDIrur4JIYbPhjNMVSaLl3XU2jhsBHXIUT/fYtR
WHZjCKg8KWzwnuLFbV0Tp8s=
-----END PRIVATE KEY-----"
client_email = "streamlit-schedule-app@my-project-schedule-458816.iam.gserviceaccount.com"
client_id = "111026163344363370027"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-schedule-app%40my-project-schedule-458816.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

